{{- define "sec" -}}
{{ .Values.user }}:{{ .Values.password }} 
{{- end -}}
{{- if .Values.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "blackbox-exporter.fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    app: {{ template "name" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  htpassword: |-
    {{ include "sec" . | b64enc }}
{{- end }}
